name: firebase

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.2.0
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2

    - name: Install dependencies
      run: npm install
    
    - name: Link Angular CLI
      run: npm link @angular/cli

    - name: Build
      run: ng build --prod
    
    - name: Install Firebase CLI
      run: npm i -g firebase-tools
    
    - name: Deploy to Firebase
      run: firebase deploy --token "$FIREBASE_TOKEN"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: amazing-pictures-12
